// <auto-generated />
using System;
using LecturaIA.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LecturaIA.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251005234302_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LecturaIA.API.Models.Entities.CodigoRegistroEstudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUso")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Usado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("DocenteId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("CodigosRegistroEstudiante");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoDocente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Institucion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoDocente")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoEstudiante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Intereses")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NivelDificultad")
                        .HasColumnType("int");

                    b.Property<string>("NivelEducativo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoEstudiante")
                        .IsUnique();

                    b.HasIndex("DocenteId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.CodigoRegistroEstudiante", b =>
                {
                    b.HasOne("LecturaIA.API.Models.Entities.Docente", "Docente")
                        .WithMany("CodigosEstudiante")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LecturaIA.API.Models.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Docente");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Docente", b =>
                {
                    b.HasOne("LecturaIA.API.Models.Entities.Usuario", "Usuario")
                        .WithOne("Docente")
                        .HasForeignKey("LecturaIA.API.Models.Entities.Docente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Estudiante", b =>
                {
                    b.HasOne("LecturaIA.API.Models.Entities.Docente", "Docente")
                        .WithMany("Estudiantes")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LecturaIA.API.Models.Entities.Usuario", "Usuario")
                        .WithOne("Estudiante")
                        .HasForeignKey("LecturaIA.API.Models.Entities.Estudiante", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Docente", b =>
                {
                    b.Navigation("CodigosEstudiante");

                    b.Navigation("Estudiantes");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Usuario", b =>
                {
                    b.Navigation("Docente");

                    b.Navigation("Estudiante");
                });
#pragma warning restore 612, 618
        }
    }
}
