// <auto-generated />
using System;
using LecturaIA.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LecturaIA.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251117035455_MakeEstudianteIdNullableForExams")]
    partial class MakeEstudianteIdNullableForExams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LecturaIA.API.Models.Entities.AsignacionExamen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Calificacion")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<int>("ExamenGrupalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SesionLecturaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("SesionLecturaId");

                    b.HasIndex("EstudianteId", "Estado");

                    b.HasIndex("ExamenGrupalId", "EstudianteId")
                        .IsUnique();

                    b.ToTable("AsignacionesExamen");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Aula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoVinculacion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoVinculacion")
                        .IsUnique();

                    b.HasIndex("DocenteId");

                    b.ToTable("Aulas");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.CodigoVerificacionLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("DireccionIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntentosRestantes")
                        .HasColumnType("int");

                    b.Property<bool>("Usado")
                        .HasColumnType("bit");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.HasIndex("UsuarioId", "FechaGeneracion");

                    b.ToTable("CodigosVerificacionLogin");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Cuestionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<int>("LecturaId")
                        .HasColumnType("int");

                    b.Property<string>("NivelDificultad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SesionLecturaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoTexto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("LecturaId");

                    b.HasIndex("SesionLecturaId")
                        .IsUnique();

                    b.ToTable("Cuestionarios");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("Grado")
                        .HasColumnType("int");

                    b.Property<string>("Intereses")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NivelDificultad")
                        .HasColumnType("int");

                    b.Property<string>("NivelEducativo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.EstudianteAula", b =>
                {
                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<int>("AulaId")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaVinculacion")
                        .HasColumnType("datetime2");

                    b.HasKey("EstudianteId", "AulaId");

                    b.HasIndex("AulaId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("EstudianteId", "Activo");

                    b.ToTable("EstudiantesAulas");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.ExamenGrupal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("AulaId")
                        .HasColumnType("int");

                    b.Property<string>("Complejidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<string>("GradoEscolar")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("LecturaId")
                        .HasColumnType("int");

                    b.Property<string>("LongitudTexto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Publicado")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("AulaId");

                    b.HasIndex("DocenteId");

                    b.HasIndex("LecturaId");

                    b.HasIndex("AulaId", "Publicado", "Activo");

                    b.ToTable("ExamenesGrupales");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Lectura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emocion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsFavorita")
                        .HasColumnType("bit");

                    b.Property<string>("Escenario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Longitud")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Personajes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Progreso")
                        .HasColumnType("int");

                    b.Property<string>("Proposito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Temas")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoLectura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("UrlImagen")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Lecturas");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Pregunta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CuestionarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Explicacion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Opciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("RespuestaCorrecta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TextoPregunta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CuestionarioId", "Orden")
                        .IsUnique();

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.RespuestaEstudiante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("EsCorrecta")
                        .HasColumnType("bit");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PuntajeIA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RetroalimentacionIA")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TextoRespuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("PreguntaId")
                        .IsUnique();

                    b.ToTable("RespuestasEstudiantes");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.ResultadoCuestionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccionNivel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CorrectasAnaliticas")
                        .HasColumnType("int");

                    b.Property<int>("CorrectasLiterales")
                        .HasColumnType("int");

                    b.Property<Guid>("CuestionarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MensajeAdaptacion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MensajeAnimo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NivelAnterior")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NivelNuevo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PuntajeCriticas")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("PuntajeTotal")
                        .HasColumnType("int");

                    b.Property<string>("RetroalimentacionPersonalizada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TiempoCuestionarioMinutos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CuestionarioId")
                        .IsUnique();

                    b.HasIndex("EstudianteId");

                    b.HasIndex("FechaEvaluacion");

                    b.ToTable("ResultadosCuestionarios");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.SesionLectura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Completada")
                        .HasColumnType("bit");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("LecturaId")
                        .HasColumnType("int");

                    b.Property<decimal>("TiempoLecturaMinutos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LecturaId");

                    b.HasIndex("EstudianteId", "LecturaId", "FechaInicio");

                    b.ToTable("SesionesLectura");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaExpiracionToken")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaReinicioPassword")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSuspension")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoReinicioPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoSuspension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PrimeraSesion")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiereDobleAutenticacion")
                        .HasColumnType("bit");

                    b.Property<bool>("Suspendido")
                        .HasColumnType("bit");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("TokenVerificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.AsignacionExamen", b =>
                {
                    b.HasOne("LecturaIA.API.Models.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LecturaIA.API.Models.Entities.ExamenGrupal", "ExamenGrupal")
                        .WithMany("Asignaciones")
                        .HasForeignKey("ExamenGrupalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LecturaIA.API.Models.Entities.SesionLectura", "SesionLectura")
                        .WithMany()
                        .HasForeignKey("SesionLecturaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Estudiante");

                    b.Navigation("ExamenGrupal");

                    b.Navigation("SesionLectura");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Aula", b =>
                {
                    b.HasOne("LecturaIA.API.Models.Entities.Docente", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.CodigoVerificacionLogin", b =>
                {
                    b.HasOne("LecturaIA.API.Models.Entities.Usuario", "Usuario")
                        .WithMany("CodigosVerificacion")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Cuestionario", b =>
                {
                    b.HasOne("LecturaIA.API.Models.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LecturaIA.API.Models.Entities.Lectura", "Lectura")
                        .WithMany()
                        .HasForeignKey("LecturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LecturaIA.API.Models.Entities.SesionLectura", "SesionLectura")
                        .WithOne("Cuestionario")
                        .HasForeignKey("LecturaIA.API.Models.Entities.Cuestionario", "SesionLecturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Lectura");

                    b.Navigation("SesionLectura");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Docente", b =>
                {
                    b.HasOne("LecturaIA.API.Models.Entities.Usuario", "Usuario")
                        .WithOne("Docente")
                        .HasForeignKey("LecturaIA.API.Models.Entities.Docente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Estudiante", b =>
                {
                    b.HasOne("LecturaIA.API.Models.Entities.Usuario", "Usuario")
                        .WithOne("Estudiante")
                        .HasForeignKey("LecturaIA.API.Models.Entities.Estudiante", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.EstudianteAula", b =>
                {
                    b.HasOne("LecturaIA.API.Models.Entities.Aula", "Aula")
                        .WithMany("Estudiantes")
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LecturaIA.API.Models.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aula");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.ExamenGrupal", b =>
                {
                    b.HasOne("LecturaIA.API.Models.Entities.Aula", "Aula")
                        .WithMany()
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LecturaIA.API.Models.Entities.Docente", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LecturaIA.API.Models.Entities.Lectura", "Lectura")
                        .WithMany()
                        .HasForeignKey("LecturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aula");

                    b.Navigation("Docente");

                    b.Navigation("Lectura");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Lectura", b =>
                {
                    b.HasOne("LecturaIA.API.Models.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Pregunta", b =>
                {
                    b.HasOne("LecturaIA.API.Models.Entities.Cuestionario", "Cuestionario")
                        .WithMany("Preguntas")
                        .HasForeignKey("CuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuestionario");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.RespuestaEstudiante", b =>
                {
                    b.HasOne("LecturaIA.API.Models.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LecturaIA.API.Models.Entities.Pregunta", "Pregunta")
                        .WithOne("Respuesta")
                        .HasForeignKey("LecturaIA.API.Models.Entities.RespuestaEstudiante", "PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.ResultadoCuestionario", b =>
                {
                    b.HasOne("LecturaIA.API.Models.Entities.Cuestionario", "Cuestionario")
                        .WithOne("Resultado")
                        .HasForeignKey("LecturaIA.API.Models.Entities.ResultadoCuestionario", "CuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LecturaIA.API.Models.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuestionario");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.SesionLectura", b =>
                {
                    b.HasOne("LecturaIA.API.Models.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LecturaIA.API.Models.Entities.Lectura", "Lectura")
                        .WithMany()
                        .HasForeignKey("LecturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Lectura");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Aula", b =>
                {
                    b.Navigation("Estudiantes");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Cuestionario", b =>
                {
                    b.Navigation("Preguntas");

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.ExamenGrupal", b =>
                {
                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Pregunta", b =>
                {
                    b.Navigation("Respuesta");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.SesionLectura", b =>
                {
                    b.Navigation("Cuestionario");
                });

            modelBuilder.Entity("LecturaIA.API.Models.Entities.Usuario", b =>
                {
                    b.Navigation("CodigosVerificacion");

                    b.Navigation("Docente");

                    b.Navigation("Estudiante");
                });
#pragma warning restore 612, 618
        }
    }
}
